---
blueprint:
  name: Dishwasher PVPC Smart Scheduling
  description: >
    Smart dishwasher scheduling based on PVPC electricity pricing.
    Automatically checks PVPC electricity prices when dishwasher is turned on.
    If price is within acceptable range, keeps dishwasher running.
    If price is too high, turns off dishwasher and schedules it to start
    during cheaper hours.

    **Required Components:**
    - PVPC Hourly Pricing integration
    - Dishwasher device (switch, smart plug, or Home Connect appliance)
    - sensor.pvpc entity providing current electricity price

    **Optional:**
    - Home Connect integration for native delayed start capability

  domain: automation
  author: bthos

  input:
    dishwasher_device:
      name: Dishwasher Device
      description: >
        Select your dishwasher device (switch, smart plug, or appliance)
      selector:
        entity:
          multiple: false

    pvpc_sensor:
      name: PVPC Price Sensor
      description: PVPC sensor entity providing current electricity price
      selector:
        entity:
          domain: sensor
      default: sensor.pvpc

    max_price_threshold:
      name: Maximum Price Threshold
      description: Maximum acceptable electricity price (€/kWh)
      selector:
        number:
          min: 0.05
          max: 0.50
          step: 0.01
          unit_of_measurement: "€/kWh"
      default: 0.15

    check_hours_ahead:
      name: Hours to Check Ahead
      description: How many hours ahead to check for cheaper prices
      selector:
        number:
          min: 1
          max: 24
          step: 1
          unit_of_measurement: hours
      default: 6

    program_duration:
      name: Dishwasher Program Duration
      description: How many hours the dishwasher program runs
      selector:
        number:
          min: 0.5
          max: 4.0
          step: 0.5
          unit_of_measurement: hours
      default: 2.0

    min_delay_minutes:
      name: Minimum Delay Before Rescheduling
      description: Minimum minutes to wait before attempting to reschedule
      selector:
        number:
          min: 5
          max: 60
          step: 5
          unit_of_measurement: minutes
      default: 30

    notification_device:
      name: Notification Device (Optional)
      description: Device to receive notifications about scheduling decisions
      selector:
        entity:
          domain:
            - notify
      default:

    use_home_connect:
      name: Use Home Connect Delayed Start
      description: >
        Enable if your dishwasher supports Home Connect and you want to use
        native delayed start instead of turning device off/on
      selector:
        boolean:
      default: false

    home_connect_program:
      name: Home Connect Program (Optional)
      description: >
        Home Connect program to start
        (e.g., 'Dishcare.Dishwasher.Program.Auto2')
        Required if using Home Connect delayed start
      selector:
        text:
      default: "Dishcare.Dishwasher.Program.Auto2"

trigger:
  - platform: state
    entity_id: !input dishwasher_device
    to: "on"

variables:
  dishwasher: !input dishwasher_device
  pvpc_sensor: !input pvpc_sensor
  max_price: !input max_price_threshold
  check_hours: !input check_hours_ahead
  program_duration: !input program_duration
  min_delay: !input min_delay_minutes
  notification_entity: !input notification_device
  use_home_connect: !input use_home_connect
  home_connect_program: !input home_connect_program

action:
  # Clean up any existing scheduled automations for this dishwasher
  - repeat:
      count: "{{ check_hours }}"
      sequence:
        - action: automation.turn_off
          target:
            entity_id: >
              automation.dishwasher_scheduled_start_{{
                (now() + timedelta(hours=repeat.index)).strftime(
                  '%Y%m%d_%H%M') }}
          continue_on_error: true

  - variables:
      current_price: "{{ states(pvpc_sensor) | float(0) }}"
      current_time: "{{ now() }}"

  # Check if current price is acceptable
  - if:
      - condition: template
        value_template: "{{ current_price <= max_price }}"
    then:
      # Price is acceptable, keep dishwasher running
      - if:
          - condition: template
            value_template: "{{ notification_entity != none }}"
        then:
          - action: "notify.{{ notification_entity.split('.')[1] }}"
            data:
              title: "Dishwasher Started"
              message: >
                Dishwasher started at acceptable price:
                {{ current_price }}€/kWh (threshold: {{ max_price }}€/kWh)
    else:
      # Price is too high, need to reschedule
      - variables:
          # Get PVPC price data using the comprehensive approach
          today_prices: >
            {{ state_attr(pvpc_sensor, 'raw_today') | default([], true) }}
          tomorrow_prices: >
            {{ state_attr(pvpc_sensor, 'raw_tomorrow') |
               default([], true) }}
          all_prices: >
            {{ state_attr(pvpc_sensor, 'prices') | default([], true) }}
          # Combine available price data
          price_data: >
            {%- set data = all_prices or (today_prices + tomorrow_prices) -%}
            {%- if data and data | length > 0 and
                data[0] is mapping -%}
              {{ data }}
            {%- else -%}
              []
            {%- endif -%}

      - variables:
          # Find cheapest consecutive hours for dishwasher program
          optimal_slot: >
            {%- set current_time = now() -%}
            {%- set end_time = current_time +
                timedelta(hours=check_hours) -%}
            {%- set duration_hours = program_duration | float -%}
            {%- set ns = namespace(best_slot=none, best_avg=999) -%}

            {%- if price_data | length > 0 -%}
              {%- for item in price_data -%}
                {%- set start_time = item.datetime | as_datetime
                    if 'datetime' in item
                    else item.start | as_datetime
                    if 'start' in item
                    else none -%}
                {%- if start_time -%}
                  {%- set start_time = start_time | as_local -%}
                  {%- set slot_end = start_time +
                      timedelta(hours=duration_hours) -%}

                  {%- if start_time >= current_time and
                      slot_end <= end_time -%}
                    {%- set ns_slot = namespace(prices=[], valid=true) -%}

                    {%- for check_item in price_data -%}
                      {%- set check_time = check_item.datetime | as_datetime
                          if 'datetime' in check_item
                          else check_item.start | as_datetime
                          if 'start' in check_item
                          else none -%}
                      {%- if check_time -%}
                        {%- set check_time = check_time | as_local -%}
                        {%- if start_time <= check_time < slot_end -%}
                          {%- set price = check_item.value | float
                              if 'value' in check_item
                              else check_item.price | float
                              if 'price' in check_item
                              else 999 -%}
                          {%- set ns_slot.prices = ns_slot.prices +
                              [price] -%}
                        {%- endif -%}
                      {%- endif -%}
                    {%- endfor -%}

                    {%- if ns_slot.prices | length >=
                        (duration_hours | round(0, 'ceil')) -%}
                      {%- set avg_price = ns_slot.prices | sum /
                          ns_slot.prices | length -%}
                      {%- if avg_price <= max_price and
                          avg_price < ns.best_avg -%}
                        {%- set ns.best_avg = avg_price -%}
                        {%- set ns.best_slot = {
                            'start_time': start_time,
                            'end_time': slot_end,
                            'avg_price': avg_price,
                            'max_price': ns_slot.prices | max,
                            'prices': ns_slot.prices
                          } -%}
                      {%- endif -%}
                    {%- endif -%}
                  {%- endif -%}
                {%- endif -%}
              {%- endfor -%}
            {%- endif -%}

            {{ ns.best_slot }}

      - if:
          - condition: template
            value_template: "{{ optimal_slot != none }}"
        then:
          # Found optimal consecutive time slot, schedule dishwasher
          - variables:
              scheduled_time: "{{ optimal_slot.start_time }}"
              scheduled_end: "{{ optimal_slot.end_time }}"
              avg_price: "{{ optimal_slot.avg_price }}"
              max_slot_price: "{{ optimal_slot.max_price }}"

          # Turn off dishwasher or set Home Connect delayed start
          - if:
              - condition: template
                value_template: "{{ use_home_connect }}"
            then:
              # Use Home Connect delayed start
              - variables:
                  delay_seconds: >
                    {{ ((scheduled_time - now()).total_seconds() | int) |
                       max(1) }}
              - action: homeconnect.set_program
                target:
                  entity_id: "{{ dishwasher }}"
                data:
                  program: "{{ home_connect_program }}"
                  options:
                    - key: "BSH.Common.Option.StartInRelative"
                      value: "{{ delay_seconds }}"
            else:
              # Turn off dishwasher for manual scheduling
              - action: homeassistant.turn_off
                target:
                  entity_id: "{{ dishwasher }}"

          # Send notification about rescheduling
          - if:
              - condition: template
                value_template: "{{ notification_entity != none }}"
            then:
              - action: "notify.{{ notification_entity.split('.')[1] }}"
                data:
                  title: "Dishwasher Rescheduled"
                  message: >
                    Current price too high: {{ current_price }}€/kWh
                    Rescheduled for {{ scheduled_time.strftime('%H:%M') }}
                    ({{ program_duration }}h program)
                    Average price: {{ avg_price | round(3) }}€/kWh
                    Max price: {{ max_slot_price | round(3) }}€/kWh

          # Wait minimum delay before creating schedule
          # (only if not using Home Connect)
          - if:
              - condition: template
                value_template: "{{ not use_home_connect }}"
            then:
              - delay:
                  minutes: "{{ min_delay }}"

          # Create automation to turn on dishwasher at scheduled time
          # (only if not using Home Connect)
          - if:
              - condition: template
                value_template: "{{ not use_home_connect }}"
            then:
              - action: automation.create
                data:
                  automation_id: >
                    dishwasher_scheduled_start_{{
                      scheduled_time.strftime('%Y%m%d_%H%M') }}
                  trigger:
                    - platform: time
                      at: "{{ scheduled_time.strftime('%H:%M') }}"
                  condition:
                    - condition: template
                      value_template: >
                        {{ states(pvpc_sensor) | float(999) <= max_price }}
                  action:
                    - action: homeassistant.turn_on
                      target:
                        entity_id: "{{ dishwasher }}"
                    - if:
                        - condition: template
                          value_template: "{{ notification_entity != none }}"
                      then:
                        - action: >
                            notify.{{
                              notification_entity.split('.')[1] }}
                          data:
                            title: "Dishwasher Started (Scheduled)"
                            message: >
                              Dishwasher started as scheduled
                              Average price: {{ avg_price | round(3) }}€/kWh
                    # Clean up this automation after running
                    - action: automation.turn_off
                      target:
                        entity_id: >
                          automation.dishwasher_scheduled_start_{{
                            scheduled_time.strftime('%Y%m%d_%H%M') }}

        else:
          # No optimal consecutive time slot found
          - if:
              - condition: template
                value_template: "{{ notification_entity != none }}"
            then:
              - action: "notify.{{ notification_entity.split('.')[1] }}"
                data:
                  title: "Dishwasher: No Optimal Schedule Found"
                  message: >
                    Current price: {{ current_price }}€/kWh (too high)
                    No {{ program_duration }}h slot found under
                    {{ max_price }}€/kWh in next {{ check_hours }} hours.
                    Dishwasher will run now despite high price.

mode: single
max_exceeded: silent
