---
blueprint:
  name: MQTT Button Light Control
  description: |
    Flexible MQTT button/knob control with customizable payload-to-action mapping.
    Map any MQTT payload to any Home Assistant action.

    **Version:** 3.0.0

    ---

    ## Features

    | Feature | Description |
    |---------|-------------|
    | **Flexible mapping** | Map any payload to any action |
    | **Multiple mappings** | Configure up to 10 payload-action pairs |
    | **Action selectors** | Use any Home Assistant action |
    | **MQTT support** | Works with any MQTT device |

    ---

    <details>
    <summary><b>How It Works</b></summary>

    1. Configure the MQTT topic that publishes button events
    2. Add payload-action mappings:
       - Enter the payload value (e.g., "toggle", "single", "rotate_left")
       - Select the action to execute when that payload is received
    3. Leave payload fields empty to disable unused mappings

    </details>

    <details>
    <summary><b>Example Configurations</b></summary>

    **Zigbee2MQTT ERS-10TZBVK-AA Smart Knob**
    - Topic: `zigbee2mqtt/ERS-10TZBVK-AA/action`
    - Mapping 1: Payload `toggle` → Action: Toggle light
    - Mapping 2: Payload `brightness_step_up` → Action: Increase brightness
    - Mapping 3: Payload `brightness_step_down` → Action: Decrease brightness

    **Generic MQTT Button**
    - Topic: `home/button/action`
    - Mapping 1: Payload `press` → Action: Turn on light
    - Mapping 2: Payload `long_press` → Action: Turn off light

    </details>

  domain: automation
  author: bthos

  input:
    mqtt_topic:
      name: MQTT Topic
      description: MQTT topic that publishes button/knob actions
      selector:
        text:
      default: "zigbee2mqtt/ERS-10TZBVK-AA/action"

    payload_action_1:
      name: Mapping 1 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_1:
      name: Mapping 1 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

    payload_action_2:
      name: Mapping 2 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_2:
      name: Mapping 2 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

    payload_action_3:
      name: Mapping 3 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_3:
      name: Mapping 3 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

    payload_action_4:
      name: Mapping 4 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_4:
      name: Mapping 4 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

    payload_action_5:
      name: Mapping 5 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_5:
      name: Mapping 5 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

    payload_action_6:
      name: Mapping 6 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_6:
      name: Mapping 6 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

    payload_action_7:
      name: Mapping 7 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_7:
      name: Mapping 7 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

    payload_action_8:
      name: Mapping 8 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_8:
      name: Mapping 8 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

    payload_action_9:
      name: Mapping 9 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_9:
      name: Mapping 9 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

    payload_action_10:
      name: Mapping 10 - Payload
      description: MQTT payload value to match (leave empty to disable)
      selector:
        text:
      default:

    action_10:
      name: Mapping 10 - Action
      description: Action to execute when payload matches
      default: []
      selector:
        action: {}

triggers:
  - trigger: mqtt
    options:
      topic: !input mqtt_topic

variables:
  payload: "{{ trigger.payload }}"
  payload_1: !input payload_action_1
  payload_2: !input payload_action_2
  payload_3: !input payload_action_3
  payload_4: !input payload_action_4
  payload_5: !input payload_action_5
  payload_6: !input payload_action_6
  payload_7: !input payload_action_7
  payload_8: !input payload_action_8
  payload_9: !input payload_action_9
  payload_10: !input payload_action_10

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ payload_1 != '' and payload == payload_1 }}"
        sequence: !input action_1

      - conditions:
          - condition: template
            value_template: "{{ payload_2 != '' and payload == payload_2 }}"
        sequence: !input action_2

      - conditions:
          - condition: template
            value_template: "{{ payload_3 != '' and payload == payload_3 }}"
        sequence: !input action_3

      - conditions:
          - condition: template
            value_template: "{{ payload_4 != '' and payload == payload_4 }}"
        sequence: !input action_4

      - conditions:
          - condition: template
            value_template: "{{ payload_5 != '' and payload == payload_5 }}"
        sequence: !input action_5

      - conditions:
          - condition: template
            value_template: "{{ payload_6 != '' and payload == payload_6 }}"
        sequence: !input action_6

      - conditions:
          - condition: template
            value_template: "{{ payload_7 != '' and payload == payload_7 }}"
        sequence: !input action_7

      - conditions:
          - condition: template
            value_template: "{{ payload_8 != '' and payload == payload_8 }}"
        sequence: !input action_8

      - conditions:
          - condition: template
            value_template: "{{ payload_9 != '' and payload == payload_9 }}"
        sequence: !input action_9

      - conditions:
          - condition: template
            value_template: "{{ payload_10 != '' and payload == payload_10 }}"
        sequence: !input action_10
