---
blueprint:
  name: Occupancy Multi-Condition Light Control
  description: |
    Generalized occupancy-based lighting control with multiple conditions and time restrictions.

    ---

    ## Features

    | Feature | Description |
    |---------|-------------|
    | **Multi-sensor support** | Multiple occupancy sensors with AND/OR logic |
    | **Time restrictions** | Day only, night only, or custom time windows |
    | **Illuminance check** | Only activate when room is dark enough |
    | **Auto turn-off** | Configurable delay before turning off |
    | **Adaptive brightness** | Dim lights at night to protect eyes |

    ---

    <details>
    <summary><b>Use Cases</b></summary>

    - **Hallways**: Multiple occupancy sensors with AND logic
    - **Living rooms**: Occupancy + low illuminance condition
    - **Bedrooms**: Night-only activation with dim brightness
    - **Bathrooms**: Immediate response with auto turn-off

    </details>

    <details>
    <summary><b>Adaptive Brightness</b></summary>

    Protects your eyes from bright light during nighttime activations:

    - **Night mode**: Reduced brightness (default 30%)
    - **Day mode**: Full brightness (default 100%)
    - **Detection**: Sun-based (automatic) or custom time window

    *Example: Wake up at 3 AM, light turns on at 30% instead of blinding 100%*

    </details>

    <details>
    <summary><b>Configuration Examples</b></summary>

    **Hallway (2 sensors)**
    - Occupancy logic: AND
    - Time restriction: Night only
    - Turn-off delay: 0 min

    **Living Room**
    - Illuminance sensor: < 500 lux
    - Turn-off delay: 15 min
    - Adaptive brightness: On

    </details>

  domain: automation
  author: bthos

  input:
    occupancy_sensors:
      name: Occupancy Sensors
      description: Select one or more occupancy sensors (binary_sensor entities)
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    occupancy_logic:
      name: Occupancy Sensor Logic
      description: How to combine multiple occupancy sensors
      selector:
        select:
          options:
            - label: "AND - All sensors must detect occupancy"
              value: "and"
            - label: "OR - Any sensor detecting occupancy"
              value: "or"
      default: "and"

    target_devices:
      name: Target Lights/Switches
      description: Select the lights or switches to control
      selector:
        entity:
          domain:
            - light
            - switch
          multiple: true

    time_restriction:
      name: Time Restriction
      description: When lights should be allowed to turn on
      selector:
        select:
          options:
            - label: "No restriction - Always allow"
              value: "none"
            - label: "Night only - After sunset, before sunrise"
              value: "night_only"
            - label: "Day only - After sunrise, before sunset"
              value: "day_only"
            - label: "Custom time window"
              value: "custom"
      default: "none"

    time_window_start:
      name: Time Window Start
      description: Start time for custom time window (HH:MM format, e.g., 18:00)
      selector:
        time:
      default:

    time_window_end:
      name: Time Window End
      description: End time for custom time window (HH:MM format, e.g., 08:00)
      selector:
        time:
      default:

    illuminance_sensor:
      name: Illuminance Sensor (Optional)
      description: Optional illuminance sensor to check before turning on lights
      selector:
        entity:
          domain: sensor
      default:

    illuminance_threshold:
      name: Illuminance Threshold (lux)
      description: Maximum illuminance level to turn on lights (below this = dark enough)
      selector:
        number:
          min: 0
          max: 10000
          step: 50
          unit_of_measurement: lux
      default: 500

    turn_off_delay:
      name: Turn Off Delay (minutes)
      description: Delay before turning off lights after occupancy clears (0 = immediate)
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: minutes
      default: 0

    transition_time:
      name: Transition Time (seconds)
      description: Transition time for lights (0-60 seconds, 0 = instant)
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: seconds
      default: 3

    adaptive_brightness_enabled:
      name: Adaptive Brightness
      description: >
        Enable adaptive brightness to dim lights at night (protects eyes from bright light).
        Full brightness during day, reduced brightness at night.
      selector:
        boolean:
      default: false

    night_brightness:
      name: Night Brightness (%)
      description: Brightness level during nighttime (0-100%)
      selector:
        number:
          min: 1
          max: 100
          step: 5
          unit_of_measurement: "%"
      default: 30

    day_brightness:
      name: Day Brightness (%)
      description: Brightness level during daytime (0-100%)
      selector:
        number:
          min: 1
          max: 100
          step: 5
          unit_of_measurement: "%"
      default: 100

    night_period_start:
      name: Night Period Start
      description: >
        When night period starts for adaptive brightness (HH:MM format).
        Use sunset-based if left empty.
      selector:
        time:
      default:

    night_period_end:
      name: Night Period End
      description: >
        When night period ends for adaptive brightness (HH:MM format).
        Use sunrise-based if left empty.
      selector:
        time:
      default:

trigger:
  - platform: state
    entity_id: !input occupancy_sensors
    id: occupancy_changed

  - platform: sun
    event: sunset
    offset: "-00:00:02"
    id: sunset_time

  - platform: sun
    event: sunrise
    offset: "00:00:02"
    id: sunrise_time

variables:
  occupancy_sensors_list: !input occupancy_sensors
  occupancy_logic_type: !input occupancy_logic
  target_devices_list: !input target_devices
  time_restriction_type: !input time_restriction
  illuminance_sensor_entity: !input illuminance_sensor
  illuminance_threshold_value: !input illuminance_threshold
  turn_off_delay_minutes: !input turn_off_delay
  transition_seconds: !input transition_time
  adaptive_brightness: !input adaptive_brightness_enabled
  night_brightness_pct: !input night_brightness
  day_brightness_pct: !input day_brightness
  night_start: !input night_period_start
  night_end: !input night_period_end

condition:
  # Time restriction check (if enabled) - skip for sunrise trigger and turn-off
  - condition: or
    conditions:
      - condition: trigger
        id: sunrise_time
      - condition: template
        value_template: "{{ time_restriction_type == 'none' }}"
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ time_restriction_type == 'night_only' }}"
          - condition: sun
            after: sunset
            before: sunrise
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ time_restriction_type == 'day_only' }}"
          - condition: sun
            after: sunrise
            before: sunset
      # Allow turn-off regardless of time restriction (if all sensors are off)
      - condition: and
        conditions:
          - condition: trigger
            id: occupancy_changed
          - condition: template
            value_template: >-
              {% set all_off = true %}
              {% for sensor in occupancy_sensors_list %}
                {% if states(sensor) == 'on' %}
                  {% set all_off = false %}
                {% endif %}
              {% endfor %}
              {{ all_off }}

  - condition: or
    conditions:
      # Occupancy changed trigger (turn ON) - check all conditions for activation
      - condition: and
        conditions:
          - condition: trigger
            id: occupancy_changed
          - condition: template
            value_template: >-
              {% set all_conditions_met = true %}
              
              {# Check occupancy sensors #}
              {% if occupancy_logic_type == 'and' %}
                {% for sensor in occupancy_sensors_list %}
                  {% if states(sensor) != 'on' %}
                    {% set all_conditions_met = false %}
                  {% endif %}
                {% endfor %}
              {% else %}
                {% set any_occupied = false %}
                {% for sensor in occupancy_sensors_list %}
                  {% if states(sensor) == 'on' %}
                    {% set any_occupied = true %}
                  {% endif %}
                {% endfor %}
                {% if not any_occupied %}
                  {% set all_conditions_met = false %}
                {% endif %}
              {% endif %}
              
              {# Check illuminance if configured #}
              {% if illuminance_sensor_entity and illuminance_sensor_entity != '' %}
                {% if (states(illuminance_sensor_entity) | float(9999)) >= illuminance_threshold_value %}
                  {% set all_conditions_met = false %}
                {% endif %}
              {% endif %}
              
              {{ all_conditions_met }}

      # Occupancy changed trigger (turn OFF) - allow when all sensors are off
      - condition: and
        conditions:
          - condition: trigger
            id: occupancy_changed
          - condition: template
            value_template: >-
              {# Check if all occupancy sensors are OFF (for turn-off logic) #}
              {% set all_off = true %}
              {% for sensor in occupancy_sensors_list %}
                {% if states(sensor) == 'on' %}
                  {% set all_off = false %}
                {% endif %}
              {% endfor %}
              {{ all_off }}

      # Sunset trigger - check if occupancy is active and night_only restriction
      - condition: and
        conditions:
          - condition: trigger
            id: sunset_time
          - condition: template
            value_template: "{{ time_restriction_type == 'night_only' }}"
          - condition: template
            value_template: >-
              {% if occupancy_logic_type == 'and' %}
                {% set all_on = true %}
                {% for sensor in occupancy_sensors_list %}
                  {% if states(sensor) != 'on' %}
                    {% set all_on = false %}
                  {% endif %}
                {% endfor %}
                {{ all_on }}
              {% else %}
                {% set any_on = false %}
                {% for sensor in occupancy_sensors_list %}
                  {% if states(sensor) == 'on' %}
                    {% set any_on = true %}
                  {% endif %}
                {% endfor %}
                {{ any_on }}
              {% endif %}

      # Sunrise trigger - always allow to turn off
      - condition: trigger
        id: sunrise_time

action:
  - choose:
      # Turn off on sunrise if night_only restriction
      - conditions:
          - condition: trigger
            id: sunrise_time
        sequence:
          - repeat:
              for_each: !input target_devices
              sequence:
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ 'light' in repeat.item }}"
                      sequence:
                        - service: light.turn_off
                          target:
                            entity_id: "{{ repeat.item }}"
                    - conditions:
                        - condition: template
                          value_template: "{{ 'switch' in repeat.item }}"
                      sequence:
                        - service: switch.turn_off
                          target:
                            entity_id: "{{ repeat.item }}"

      # Turn on when conditions are met
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: occupancy_changed
              - condition: trigger
                id: sunset_time
        sequence:
          - variables:
              should_turn_on: >-
                {% set all_conditions_met = true %}
                
                {# Check occupancy sensors #}
                {% if occupancy_logic_type == 'and' %}
                  {% for sensor in occupancy_sensors_list %}
                    {% if states(sensor) != 'on' %}
                      {% set all_conditions_met = false %}
                    {% endif %}
                  {% endfor %}
                {% else %}
                  {% set any_occupied = false %}
                  {% for sensor in occupancy_sensors_list %}
                    {% if states(sensor) == 'on' %}
                      {% set any_occupied = true %}
                    {% endif %}
                  {% endfor %}
                  {% if not any_occupied %}
                    {% set all_conditions_met = false %}
                  {% endif %}
                {% endif %}
                
                {# Check time restriction - handled via separate condition #}
                
                {# Check illuminance if configured #}
                {% if illuminance_sensor_entity and illuminance_sensor_entity != '' %}
                  {% if (states(illuminance_sensor_entity) | float(9999)) >= illuminance_threshold_value %}
                    {% set all_conditions_met = false %}
                  {% endif %}
                {% endif %}
                
                {{ all_conditions_met }}

          - condition: template
            value_template: "{{ should_turn_on }}"

          - variables:
              # Calculate brightness based on adaptive brightness settings
              target_brightness: >-
                {% if not adaptive_brightness %}
                  {# Adaptive brightness disabled - use day brightness #}
                  {{ day_brightness_pct }}
                {% else %}
                  {# Check if it's night period #}
                  {% set is_night = false %}
                  {% if night_start and night_end %}
                    {# Use custom night period #}
                    {% set now_time = now().strftime('%H:%M') %}
                    {% set start_time = night_start %}
                    {% set end_time = night_end %}
                    {% if start_time > end_time %}
                      {# Night period spans midnight (e.g., 22:00 - 06:00) #}
                      {% if now_time >= start_time or now_time < end_time %}
                        {% set is_night = true %}
                      {% endif %}
                    {% else %}
                      {# Night period within same day #}
                      {% if now_time >= start_time and now_time < end_time %}
                        {% set is_night = true %}
                      {% endif %}
                    {% endif %}
                  {% else %}
                    {# Use sun-based night period (after sunset, before sunrise) #}
                    {% if states('sun.sun') == 'below_horizon' %}
                      {% set is_night = true %}
                    {% endif %}
                  {% endif %}
                  {% if is_night %}
                    {{ night_brightness_pct }}
                  {% else %}
                    {{ day_brightness_pct }}
                  {% endif %}
                {% endif %}

          - repeat:
              for_each: !input target_devices
              sequence:
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ 'light' in repeat.item }}"
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: "{{ repeat.item }}"
                          data:
                            transition: "{{ transition_seconds }}"
                            brightness_pct: "{{ target_brightness }}"
                    - conditions:
                        - condition: template
                          value_template: "{{ 'switch' in repeat.item }}"
                      sequence:
                        - service: switch.turn_on
                          target:
                            entity_id: "{{ repeat.item }}"

      # Turn off when occupancy clears (with delay if configured)
      - conditions:
          - condition: trigger
            id: occupancy_changed
          - condition: template
            value_template: >-
              {% if occupancy_logic_type == 'and' %}
                {% set all_off = true %}
                {% for sensor in occupancy_sensors_list %}
                  {% if states(sensor) == 'on' %}
                    {% set all_off = false %}
                  {% endif %}
                {% endfor %}
                {{ all_off }}
              {% else %}
                {% set all_off = true %}
                {% for sensor in occupancy_sensors_list %}
                  {% if states(sensor) == 'on' %}
                    {% set all_off = false %}
                  {% endif %}
                {% endfor %}
                {{ all_off }}
              {% endif %}
        sequence:
          - delay:
              minutes: "{{ turn_off_delay_minutes }}"
          - condition: template
            value_template: >-
              {% if occupancy_logic_type == 'and' %}
                {% set all_off = true %}
                {% for sensor in occupancy_sensors_list %}
                  {% if states(sensor) == 'on' %}
                    {% set all_off = false %}
                  {% endif %}
                {% endfor %}
                {{ all_off }}
              {% else %}
                {% set all_off = true %}
                {% for sensor in occupancy_sensors_list %}
                  {% if states(sensor) == 'on' %}
                    {% set all_off = false %}
                  {% endif %}
                {% endfor %}
                {{ all_off }}
              {% endif %}
          - repeat:
              for_each: !input target_devices
              sequence:
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ 'light' in repeat.item }}"
                      sequence:
                        - service: light.turn_off
                          target:
                            entity_id: "{{ repeat.item }}"
                    - conditions:
                        - condition: template
                          value_template: "{{ 'switch' in repeat.item }}"
                      sequence:
                        - service: switch.turn_off
                          target:
                            entity_id: "{{ repeat.item }}"

mode: single
max_exceeded: silent
